# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
# Fabric Properties (ver https://fabricmc.net/develop)
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.1
loader_version=0.16.14
# Loom
loom_version=1.9-SNAPSHOT
# Mod Properties
mod_version=1.0.0
maven_group=com.mazerunner
archives_base_name=mazerunner
# Dependencies
fabric_version=0.116.4+1.21.1
